# Generated by Django 3.0.4 on 2020-04-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torshavn_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draggable', models.BooleanField()),
                ('animation', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('icon_path', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
